api_login_check:
    path: /api/v1/login_check

app.swagger_ui:
    path: /api/v1/documentation
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
